require('settings')
require('keybinds')
require('plugins')
require('theme')
-- require('nr-autocommands')
-- require('nr-autopairs')
-- require('nr-barbar')
-- require('nr-colorizer')
-- require('nr-comment')
-- require('nr-compe')
-- require('nr-floatterm')
-- require('nr-galaxy-line')
-- require('nr-gitsigns')
-- require('nr-lsp-install')
-- require('nr-lsp-saga')
-- require('nr-nvim-tree')
-- require('nr-rooter')
-- require('nr-telescope')
-- require('nr-todo-comments')
-- require('nr-treesitter')
-- require('nr-trouble')
-- require('nr-utils')
-- require('nr-which-key')

-- LSP
require('lsp')
require('lsp.ruby-ls')
